### ISSUE TITLE
Transfer ownership to remark

### ISSUE THREAD

**Issue by Rokt33r** [remarkjs/remark-math#30]
As I commented here, I want to transfer ownership of this repo to remark.
https://github.com/mdx-js/mdx/issues/712#issuecomment-518907816

@wooorm Could you tell me what should I do?

**Comment by wooorm** [comment]
This process is called a [governance grant](https://github.com/unifiedjs/governance/blob/master/governance-grant.md), except that those docs are for outside maintainers (you’re a member).

#### Steps for you

- You may be able to move the project into the @remarkjs GitHub organisation. Otherwise you can transfer the repo to me and I can do that.
- Next would be to give me admin access on npm as well

#### Further steps

- I’ll update the readmes to match the rest of the collective
- GitHub and npm tools will automatically update GH and npm access within 24 hours.

**Comment by Rokt33r** [comment]
> Steps for you

@wooorm Done!

**Comment by wooorm** [comment]
Sweet!

**Comment by wooorm** [comment]
Done!
